<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_CommonBasePropsImported>true</_CommonBasePropsImported>
    <PublicIncludeDirectories>$(MSBuildThisFileDirectory);$(PublicIncludeDirectories)</PublicIncludeDirectories>
    <CommonBaseInheritedPreprocessorDefinitions></CommonBaseInheritedPreprocessorDefinitions>
    <CommonBaseInheritedPreprocessorDefinitions Condition="'$(Configuration)' == 'Debug'">KEYH_DEBUG;KEYH_DEV;</CommonBaseInheritedPreprocessorDefinitions>
    <CommonBaseInheritedPreprocessorDefinitions Condition="'$(Configuration)' == 'DevRelease'">KEYH_DEV;</CommonBaseInheritedPreprocessorDefinitions>
    <CommonBaseInheritedPreprocessorDefinitions Condition="'$(CommonBaseInheritedPreprocessorDefinitions)' == '' and '$(Configuration)' == 'Release' and $([System.String]::Copy('$(CurrentSolutionConfigurationContents)').Contains('&lt;SolutionConfiguration&gt;DevRelease|'))">KEYH_DEV;</CommonBaseInheritedPreprocessorDefinitions>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>$(CommonBaseInheritedPreprocessorDefinitions);%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ForcedIncludeFiles>%(ForcedIncludeFiles);CommonBasePch.h;CommonCore.h;AssertUtil.h;FileUtil.h;HashUtil.h;MathUtil.h;MemoryUtil.h;SimdUtil.h;StrUtil.h;StringView.h;StaticString.h;FlyweightString.h;SplitterString.h;Ptr.h;RefPtr.h;WeakPtr.h;HashMap.h;HashSet.h;Vector.h;OwnerVector.h;InlinedVector.h;IBuffer.h;StaticBuffer.h;DynamicBuffer.h;File.h;FileWriter.h;Delegate.h;</ForcedIncludeFiles>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
