<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\CommonBase\CommonBase.props" Condition="'$(_CommonBasePropsImported)' != 'true'" />
  <PropertyGroup>
    <_ReflectSystemPropsImported>true</_ReflectSystemPropsImported>
    <PublicIncludeDirectories>$(MSBuildThisFileDirectory);$(PublicIncludeDirectories)</PublicIncludeDirectories>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
	  <ForcedIncludeFiles>%(ForcedIncludeFiles);ReflectionUtil.h;IReflectProperty.h;IReflectObject.h;ReflectMetaObject.h;ReflectObject.h;ReflectProperty.h;ReflectPropertyPolicy.h;ReflectSerializer.h</ForcedIncludeFiles>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
