// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-07-11 06:55:43
//
// Include this file from a dedicated .cpp that already includes:
//   1. Your project precompiled header
//   2. "ReflectObject.h" (for the template specialisations)
//   3. Each header that declares a REFLECTIVE class, e.g.:
//        #include "test.h"
//   4. #include "reflect_generated.inl"
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)..\Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	ReflectMetaObject ReflectObject<TestObject>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		static const FlyweightStringA sGroupName_Group1("Group1");

		metaObject.addReflectProperty<TestObject, int>(
			FlyweightStringA("_intValue"),
			sGroupName_Group1,
			0,
			[](TestObject& obj) -> int& { return obj._intValue; },
			[](const TestObject& obj) -> const int& { return obj._intValue; }
		);

		metaObject.addReflectProperty<TestObject, float>(
			FlyweightStringA("FloatValue"),
			sGroupName_Group1,
			0.0f,
			[](TestObject& obj) -> float& { return obj._floatValue; },
			[](const TestObject& obj) -> const float& { return obj._floatValue; }
		);

		metaObject.addReflectProperty<TestObject, StaticStringA>(
			FlyweightStringA("_stringValue"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](TestObject& obj) -> StaticStringA& { return obj._stringValue; },
			[](const TestObject& obj) -> const StaticStringA& { return obj._stringValue; }
		);

		return metaObject;
	}
}
