// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-07-10 22:25:15
//
// This file is automatically #include-d at the end of each REFLECTIVE header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header(s) if not already present:
//   test.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<TestObject>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		static const FlyweightStringA sGroupName_Group1("Group1");

		metaObject.addReflectProperty<TestObject, int>(
			FlyweightStringA("_intValue"),
			sGroupName_Group1,
			0,
			[](TestObject& obj) -> int& { return obj._intValue; },
			[](const TestObject& obj) -> const int& { return obj._intValue; }
		);

		metaObject.addReflectProperty<TestObject, float>(
			FlyweightStringA("FloatValue"),
			sGroupName_Group1,
			0.0f,
			[](TestObject& obj) -> float& { return obj._floatValue; },
			[](const TestObject& obj) -> const float& { return obj._floatValue; }
		);

		metaObject.addReflectProperty<TestObject, StaticStringA>(
			FlyweightStringA("_stringValue"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](TestObject& obj) -> StaticStringA& { return obj._stringValue; },
			[](const TestObject& obj) -> const StaticStringA& { return obj._stringValue; }
		);

		return metaObject;
	}
}
