// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-08-29 23:04:56
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   test.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<TestDeepObject>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<TestDeepObject, Vector<StaticStringA>>(
			FlyweightStringA("Tags"),
			FlyweightStringA::Empty,
			Vector<StaticStringA>{},
			[](TestDeepObject& obj) -> Vector<StaticStringA>& { return obj._tags; },
			[](const TestDeepObject& obj) -> const Vector<StaticStringA>& { return obj._tags; }
		);

		metaObject.addReflectProperty<TestDeepObject, int>(
			FlyweightStringA("Counter"),
			FlyweightStringA::Empty,
			0,
			[](TestDeepObject& obj) -> int& { return obj._counter; },
			[](const TestDeepObject& obj) -> const int& { return obj._counter; }
		);

		return metaObject;
	}
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<TestNestedObject>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<TestNestedObject, Vector<StaticStringA>>(
			FlyweightStringA("Labels"),
			FlyweightStringA::Empty,
			Vector<StaticStringA>{},
			[](TestNestedObject& obj) -> Vector<StaticStringA>& { return obj._labels; },
			[](const TestNestedObject& obj) -> const Vector<StaticStringA>& { return obj._labels; }
		);

		metaObject.addReflectProperty<TestNestedObject, TestDeepObject>(
			FlyweightStringA("Deep"),
			FlyweightStringA::Empty,
			TestDeepObject{},
			[](TestNestedObject& obj) -> TestDeepObject& { return obj._deep; },
			[](const TestNestedObject& obj) -> const TestDeepObject& { return obj._deep; }
		);

		metaObject.addReflectProperty<TestNestedObject, float>(
			FlyweightStringA("Score"),
			FlyweightStringA::Empty,
			0.0f,
			[](TestNestedObject& obj) -> float& { return obj._score; },
			[](const TestNestedObject& obj) -> const float& { return obj._score; }
		);

		return metaObject;
	}
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<TestSubObject>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<TestSubObject, Vector<StaticStringA>>(
			FlyweightStringA("Names"),
			FlyweightStringA::Empty,
			Vector<StaticStringA>{},
			[](TestSubObject& obj) -> Vector<StaticStringA>& { return obj._names; },
			[](const TestSubObject& obj) -> const Vector<StaticStringA>& { return obj._names; }
		);

		return metaObject;
	}
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<TestObject>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		static const FlyweightStringA sGroupName_Group1("Group1");

		metaObject.addReflectProperty<TestObject, int>(
			FlyweightStringA("_intValue"),
			sGroupName_Group1,
			0,
			[](TestObject& obj) -> int& { return obj._intValue; },
			[](const TestObject& obj) -> const int& { return obj._intValue; }
		);

		metaObject.addReflectProperty<TestObject, float>(
			FlyweightStringA("FloatValue"),
			sGroupName_Group1,
			0.0f,
			[](TestObject& obj) -> float& { return obj._floatValue; },
			[](const TestObject& obj) -> const float& { return obj._floatValue; }
		);

		metaObject.addReflectProperty<TestObject, StaticStringA>(
			FlyweightStringA("_stringValue"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](TestObject& obj) -> StaticStringA& { return obj._stringValue; },
			[](const TestObject& obj) -> const StaticStringA& { return obj._stringValue; }
		);

		metaObject.addReflectProperty<TestObject, Vector<StaticStringA>>(
			FlyweightStringA("Names"),
			FlyweightStringA::Empty,
			Vector<StaticStringA>{},
			[](TestObject& obj) -> Vector<StaticStringA>& { return obj._names; },
			[](const TestObject& obj) -> const Vector<StaticStringA>& { return obj._names; }
		);

		metaObject.addReflectProperty<TestObject, TestSubObject>(
			FlyweightStringA("SubObject"),
			FlyweightStringA::Empty,
			TestSubObject{},
			[](TestObject& obj) -> TestSubObject& { return obj._subObject; },
			[](const TestObject& obj) -> const TestSubObject& { return obj._subObject; }
		);

		metaObject.addReflectProperty<TestObject, TestNestedObject>(
			FlyweightStringA("Nested"),
			FlyweightStringA::Empty,
			TestNestedObject{},
			[](TestObject& obj) -> TestNestedObject& { return obj._nested; },
			[](const TestObject& obj) -> const TestNestedObject& { return obj._nested; }
		);

		return metaObject;
	}
}
