// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhCommon Reflect Code Generator
//
// Automatically included at the end of the matching source file
// by reflect_codegen.py; do not edit this generated file.
//   ResourcePathManager.h

namespace keyh
{
	template<>
	ReflectMetaObject ReflectObject<ProjectNode>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<ProjectNode, EProjectPath>(
			FlyweightStringA("ProjectPath"),
			FlyweightStringA::Empty,
			[](const EProjectPath& value) -> bool { return ReflectPropertyPolicy<EProjectPath>::isDefault(value); },
			[](ProjectNode& obj) -> EProjectPath& { return obj._projectPath; },
			[](const ProjectNode& obj) -> const EProjectPath& { return obj._projectPath; }
		);

		metaObject.addReflectProperty<ProjectNode, Vector<ProjectNode>>(
			FlyweightStringA("Children"),
			FlyweightStringA::Empty,
			[](const Vector<ProjectNode>& value) -> bool { return ReflectPropertyPolicy<Vector<ProjectNode>>::isDefault(value); },
			[](ProjectNode& obj) -> Vector<ProjectNode>& { return obj._children; },
			[](const ProjectNode& obj) -> const Vector<ProjectNode>& { return obj._children; }
		);

		return metaObject;
	}
}
