// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-09-12 11:56:27
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialParameterView.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialParameterView>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialParameterView, MaterialParameterType>(
			FlyweightStringA("Type"),
			FlyweightStringA::Empty,
			MaterialParameterType{},
			[](MaterialParameterView& obj) -> MaterialParameterType& { return obj._parameterType; },
			[](const MaterialParameterView& obj) -> const MaterialParameterType& { return obj._parameterType; }
		);

		metaObject.addReflectProperty<MaterialParameterView, uint32>(
			FlyweightStringA("Offset"),
			FlyweightStringA::Empty,
			uint32{},
			[](MaterialParameterView& obj) -> uint32& { return obj._offset; },
			[](const MaterialParameterView& obj) -> const uint32& { return obj._offset; }
		);

		return metaObject;
	}
}
