// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-09-10 16:21:16
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialDefinition.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialDefinition>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialDefinition, FlyweightStringA>(
			FlyweightStringA("MaterialName"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialDefinition& obj) -> FlyweightStringA& { return obj._materialName; },
			[](const MaterialDefinition& obj) -> const FlyweightStringA& { return obj._materialName; }
		);

		metaObject.addReflectProperty<MaterialDefinition, OwnerVector<MaterialBitFlagDefinition>>(
			FlyweightStringA("MaterialBitFlagDefinitions"),
			FlyweightStringA::Empty,
			OwnerVector<MaterialBitFlagDefinition>{},
			[](MaterialDefinition& obj) -> OwnerVector<MaterialBitFlagDefinition>& { return obj._materialBitFlagDefinitions; },
			[](const MaterialDefinition& obj) -> const OwnerVector<MaterialBitFlagDefinition>& { return obj._materialBitFlagDefinitions; }
		);

		metaObject.addReflectProperty<MaterialDefinition, OwnerVector<MaterialParameterDefinition>>(
			FlyweightStringA("MaterialParameterDefinitions"),
			FlyweightStringA::Empty,
			OwnerVector<MaterialParameterDefinition>{},
			[](MaterialDefinition& obj) -> OwnerVector<MaterialParameterDefinition>& { return obj._materialParameterDefinitions; },
			[](const MaterialDefinition& obj) -> const OwnerVector<MaterialParameterDefinition>& { return obj._materialParameterDefinitions; }
		);

		return metaObject;
	}
}
