// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-09-12 23:11:36
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialLayout.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialLayout>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialLayout, MaterialBitFlagViews>(
			FlyweightStringA("MaterialBitFlagViews"),
			FlyweightStringA::Empty,
			MaterialBitFlagViews{},
			[](MaterialLayout& obj) -> MaterialBitFlagViews& { return obj._materialBitFlagViews; },
			[](const MaterialLayout& obj) -> const MaterialBitFlagViews& { return obj._materialBitFlagViews; }
		);

		metaObject.addReflectProperty<MaterialLayout, MaterialParameterViews>(
			FlyweightStringA("MaterialParameterViews"),
			FlyweightStringA::Empty,
			MaterialParameterViews{},
			[](MaterialLayout& obj) -> MaterialParameterViews& { return obj._materialParameterViews; },
			[](const MaterialLayout& obj) -> const MaterialParameterViews& { return obj._materialParameterViews; }
		);

		metaObject.addReflectProperty<MaterialLayout, DynamicBuffer<byte>>(
			FlyweightStringA("MaterialMemorySize"),
			FlyweightStringA::Empty,
			DynamicBuffer<byte>{},
			[](MaterialLayout& obj) -> DynamicBuffer<byte>& { return obj._gpuMaterialMemoryBlock; },
			[](const MaterialLayout& obj) -> const DynamicBuffer<byte>& { return obj._gpuMaterialMemoryBlock; }
		);

		return metaObject;
	}
}
