// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
//
// This file is automatically #include-d at the end of its REFLECTIVE header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialInfo.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialInfo, FlyweightStringA>(
			FlyweightStringA("MaterialName"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialInfo& obj) -> FlyweightStringA& { return obj._materialName; },
			[](const MaterialInfo& obj) -> const FlyweightStringA& { return obj._materialName; }
		);

		metaObject.addReflectProperty<MaterialInfo, OwnerVector<MaterialParameterInfo>>(
			FlyweightStringA("MaterialParameterInfos"),
			FlyweightStringA::Empty,
			OwnerVector<MaterialParameterInfo>{},
			[](MaterialInfo& obj) -> OwnerVector<MaterialParameterInfo>& { return obj._materialParameterInfos; },
			[](const MaterialInfo& obj) -> const OwnerVector<MaterialParameterInfo>& { return obj._materialParameterInfos; }
		);

		return metaObject;
	}
}
