// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-08-26 22:46:04
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialParameterInfo.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	KEYH_REFLECT_ENUM_BEGIN(MaterialParameterType)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Int)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Int2)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Float)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Float2)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Float3)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Float4)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Transform)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Texture)
	KEYH_REFLECT_ENUM_END(MaterialParameterType)
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialParameterInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialParameterInfo, FlyweightStringA>(
			FlyweightStringA("Name"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialParameterInfo& obj) -> FlyweightStringA& { return obj._parameterName; },
			[](const MaterialParameterInfo& obj) -> const FlyweightStringA& { return obj._parameterName; }
		);

		metaObject.addReflectProperty<MaterialParameterInfo, MaterialParameterType>(
			FlyweightStringA("Type"),
			FlyweightStringA::Empty,
			MaterialParameterType{},
			[](MaterialParameterInfo& obj) -> MaterialParameterType& { return obj._parameterType; },
			[](const MaterialParameterInfo& obj) -> const MaterialParameterType& { return obj._parameterType; }
		);

		metaObject.addReflectProperty<MaterialParameterInfo, StaticStringA>(
			FlyweightStringA("Desc"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](MaterialParameterInfo& obj) -> StaticStringA& { return obj._description; },
			[](const MaterialParameterInfo& obj) -> const StaticStringA& { return obj._description; }
		);

		return metaObject;
	}
}
