// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
//
// This file is automatically #include-d at the end of its REFLECTIVE header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialParameterInfo.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialParameterInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialParameterInfo, FlyweightStringA>(
			FlyweightStringA("ParameterName"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialParameterInfo& obj) -> FlyweightStringA& { return obj._parameterNames; },
			[](const MaterialParameterInfo& obj) -> const FlyweightStringA& { return obj._parameterNames; }
		);

		return metaObject;
	}
}
