// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-09-12 11:55:23
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialEnum.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	KEYH_REFLECT_ENUM_BEGIN(MaterialParameterType)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Unknown)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Int)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Int2)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Float)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Float2)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Float3)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, Float4)
		KEYH_REFLECT_ENUM_VALUE(MaterialParameterType, ReferencedPath_Texture)
	KEYH_REFLECT_ENUM_END(MaterialParameterType)
}
