// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-09-12 11:55:23
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialParameterDefinition.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialBitFlagDefinition>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialBitFlagDefinition, FlyweightStringA>(
			FlyweightStringA("Name"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialBitFlagDefinition& obj) -> FlyweightStringA& { return obj._parameterName; },
			[](const MaterialBitFlagDefinition& obj) -> const FlyweightStringA& { return obj._parameterName; }
		);

		metaObject.addReflectProperty<MaterialBitFlagDefinition, uint8>(
			FlyweightStringA("BitIndex"),
			FlyweightStringA::Empty,
			uint8{},
			[](MaterialBitFlagDefinition& obj) -> uint8& { return obj._bitIndex; },
			[](const MaterialBitFlagDefinition& obj) -> const uint8& { return obj._bitIndex; }
		);

		metaObject.addReflectProperty<MaterialBitFlagDefinition, bool>(
			FlyweightStringA("DefaultValue"),
			FlyweightStringA::Empty,
			bool{},
			[](MaterialBitFlagDefinition& obj) -> bool& { return obj._defaultValue; },
			[](const MaterialBitFlagDefinition& obj) -> const bool& { return obj._defaultValue; }
		);

		metaObject.addReflectProperty<MaterialBitFlagDefinition, StaticStringA>(
			FlyweightStringA("Desc"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](MaterialBitFlagDefinition& obj) -> StaticStringA& { return obj._description; },
			[](const MaterialBitFlagDefinition& obj) -> const StaticStringA& { return obj._description; }
		);

		return metaObject;
	}
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialParameterDefinition>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialParameterDefinition, FlyweightStringA>(
			FlyweightStringA("Name"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialParameterDefinition& obj) -> FlyweightStringA& { return obj._parameterName; },
			[](const MaterialParameterDefinition& obj) -> const FlyweightStringA& { return obj._parameterName; }
		);

		metaObject.addReflectProperty<MaterialParameterDefinition, MaterialParameterType>(
			FlyweightStringA("Type"),
			FlyweightStringA::Empty,
			MaterialParameterType{},
			[](MaterialParameterDefinition& obj) -> MaterialParameterType& { return obj._parameterType; },
			[](const MaterialParameterDefinition& obj) -> const MaterialParameterType& { return obj._parameterType; }
		);

		metaObject.addReflectProperty<MaterialParameterDefinition, StaticStringA>(
			FlyweightStringA("DefaultValue"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](MaterialParameterDefinition& obj) -> StaticStringA& { return obj._defaultValue; },
			[](const MaterialParameterDefinition& obj) -> const StaticStringA& { return obj._defaultValue; }
		);

		metaObject.addReflectProperty<MaterialParameterDefinition, StaticStringA>(
			FlyweightStringA("Desc"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](MaterialParameterDefinition& obj) -> StaticStringA& { return obj._description; },
			[](const MaterialParameterDefinition& obj) -> const StaticStringA& { return obj._description; }
		);

		return metaObject;
	}
}
