// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-09-02 13:30:46
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialParameterInfo.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialBitFlagParameterInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialBitFlagParameterInfo, FlyweightStringA>(
			FlyweightStringA("Name"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialBitFlagParameterInfo& obj) -> FlyweightStringA& { return obj._parameterName; },
			[](const MaterialBitFlagParameterInfo& obj) -> const FlyweightStringA& { return obj._parameterName; }
		);

		metaObject.addReflectProperty<MaterialBitFlagParameterInfo, uint8>(
			FlyweightStringA("BitIndex"),
			FlyweightStringA::Empty,
			uint8{},
			[](MaterialBitFlagParameterInfo& obj) -> uint8& { return obj._bitIndex; },
			[](const MaterialBitFlagParameterInfo& obj) -> const uint8& { return obj._bitIndex; }
		);

		metaObject.addReflectProperty<MaterialBitFlagParameterInfo, bool>(
			FlyweightStringA("DefaultValue"),
			FlyweightStringA::Empty,
			bool{},
			[](MaterialBitFlagParameterInfo& obj) -> bool& { return obj._defaultValue; },
			[](const MaterialBitFlagParameterInfo& obj) -> const bool& { return obj._defaultValue; }
		);

		metaObject.addReflectProperty<MaterialBitFlagParameterInfo, StaticStringA>(
			FlyweightStringA("Desc"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](MaterialBitFlagParameterInfo& obj) -> StaticStringA& { return obj._description; },
			[](const MaterialBitFlagParameterInfo& obj) -> const StaticStringA& { return obj._description; }
		);

		return metaObject;
	}
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialParameterInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialParameterInfo, FlyweightStringA>(
			FlyweightStringA("Name"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialParameterInfo& obj) -> FlyweightStringA& { return obj._parameterName; },
			[](const MaterialParameterInfo& obj) -> const FlyweightStringA& { return obj._parameterName; }
		);

		metaObject.addReflectProperty<MaterialParameterInfo, MaterialParameterType>(
			FlyweightStringA("Type"),
			FlyweightStringA::Empty,
			MaterialParameterType{},
			[](MaterialParameterInfo& obj) -> MaterialParameterType& { return obj._parameterType; },
			[](const MaterialParameterInfo& obj) -> const MaterialParameterType& { return obj._parameterType; }
		);

		metaObject.addReflectProperty<MaterialParameterInfo, StaticStringA>(
			FlyweightStringA("DefaultValue"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](MaterialParameterInfo& obj) -> StaticStringA& { return obj._defaultValue; },
			[](const MaterialParameterInfo& obj) -> const StaticStringA& { return obj._defaultValue; }
		);

		metaObject.addReflectProperty<MaterialParameterInfo, StaticStringA>(
			FlyweightStringA("Desc"),
			FlyweightStringA::Empty,
			StaticStringA{},
			[](MaterialParameterInfo& obj) -> StaticStringA& { return obj._description; },
			[](const MaterialParameterInfo& obj) -> const StaticStringA& { return obj._description; }
		);

		metaObject.addReflectProperty<MaterialParameterInfo, Vector<MaterialBitFlagParameterInfo>>(
			FlyweightStringA("BitFlagInfo"),
			FlyweightStringA::Empty,
			Vector<MaterialBitFlagParameterInfo>{},
			[](MaterialParameterInfo& obj) -> Vector<MaterialBitFlagParameterInfo>& { return obj._bitFlagInfos; },
			[](const MaterialParameterInfo& obj) -> const Vector<MaterialBitFlagParameterInfo>& { return obj._bitFlagInfos; }
		);

		return metaObject;
	}
}
