// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-09-20 10:59:41
//
// This file is automatically #include-d at the end of its REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header if not already present:
//   MaterialLayoutRegistry.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialLayoutRegistry>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialLayoutRegistry, MaterialGroupTable>(
			FlyweightStringA("MaterialGroupTables"),
			FlyweightStringA::Empty,
			MaterialGroupTable{},
			[](MaterialLayoutRegistry& obj) -> MaterialGroupTable& { return obj._materialGroupTables; },
			[](const MaterialLayoutRegistry& obj) -> const MaterialGroupTable& { return obj._materialGroupTables; }
		);

		return metaObject;
	}
}
