// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
//
// This file is automatically #include-d at the end of each REFLECTIVE header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header(s) if not already present:
//   MaterialParameterInfo.h
//   MaterialInfo.h
#pragma once

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialParameterInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialParameterInfo, FlyweightStringA>(
			FlyweightStringA("ParameterName"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialParameterInfo& obj) -> FlyweightStringA& { return obj._parameterNames; },
			[](const MaterialParameterInfo& obj) -> const FlyweightStringA& { return obj._parameterNames; }
		);

		return metaObject;
	}
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialInfo, FlyweightStringA>(
			FlyweightStringA("MaterialName"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialInfo& obj) -> FlyweightStringA& { return obj._materialName; },
			[](const MaterialInfo& obj) -> const FlyweightStringA& { return obj._materialName; }
		);

		metaObject.addReflectProperty<MaterialInfo, OwnerVector<MaterialParameterInfo>>(
			FlyweightStringA("MaterialParameterInfos"),
			FlyweightStringA::Empty,
			OwnerVector<MaterialParameterInfo>{},
			[](MaterialInfo& obj) -> OwnerVector<MaterialParameterInfo>& { return obj._materialParameterInfos; },
			[](const MaterialInfo& obj) -> const OwnerVector<MaterialParameterInfo>& { return obj._materialParameterInfos; }
		);

		return metaObject;
	}
}
