// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by KeyhEngine Reflect Code Generator
// Generated at: 2026-08-26 13:06:40
//
// This file is automatically #include-d at the end of each REFLECTIVE/KEYH_REFLECT_ENUM header
// by the code generator (reflect_codegen.py).  You do not need to include it
// manually; re-run the generator (or let the pre-build event do it) and it
// will be appended to the following header(s) if not already present:
//   MaterialInfo.h
//   MaterialParameterInfo.h
//
// Pre-build event snippet for .vcxproj:
//   <PreBuildEvent>
//     <Command>call "$(SolutionDir)Tools\run_reflect_codegen.bat"
//              "$(ProjectDir)."</Command>
//   </PreBuildEvent>

namespace keyh
{
	KEYH_REFLECT_ENUM_BEGIN(EMaterialParamType)
		KEYH_REFLECT_ENUM_VALUE(EMaterialParamType, Int)
		KEYH_REFLECT_ENUM_VALUE(EMaterialParamType, Int2)
		KEYH_REFLECT_ENUM_VALUE(EMaterialParamType, Float)
		KEYH_REFLECT_ENUM_VALUE(EMaterialParamType, Float2)
		KEYH_REFLECT_ENUM_VALUE(EMaterialParamType, Float3)
		KEYH_REFLECT_ENUM_VALUE(EMaterialParamType, Float4)
		KEYH_REFLECT_ENUM_VALUE(EMaterialParamType, Matrix4x4)
		KEYH_REFLECT_ENUM_VALUE(EMaterialParamType, TextureReferencePath)
	KEYH_REFLECT_ENUM_END()
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialInfo, FlyweightStringA>(
			FlyweightStringA("MaterialName"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialInfo& obj) -> FlyweightStringA& { return obj._materialName; },
			[](const MaterialInfo& obj) -> const FlyweightStringA& { return obj._materialName; }
		);

		metaObject.addReflectProperty<MaterialInfo, OwnerVector<MaterialParameterInfo>>(
			FlyweightStringA("MaterialParameterInfos"),
			FlyweightStringA::Empty,
			OwnerVector<MaterialParameterInfo>{},
			[](MaterialInfo& obj) -> OwnerVector<MaterialParameterInfo>& { return obj._materialParameterInfos; },
			[](const MaterialInfo& obj) -> const OwnerVector<MaterialParameterInfo>& { return obj._materialParameterInfos; }
		);

		return metaObject;
	}
}

namespace keyh
{
	template<>
	inline ReflectMetaObject ReflectObject<MaterialParameterInfo>::initializeMetaObject()
	{
		ReflectMetaObject metaObject;

		metaObject.addReflectProperty<MaterialParameterInfo, FlyweightStringA>(
			FlyweightStringA("ParameterName"),
			FlyweightStringA::Empty,
			FlyweightStringA{},
			[](MaterialParameterInfo& obj) -> FlyweightStringA& { return obj._parameterNames; },
			[](const MaterialParameterInfo& obj) -> const FlyweightStringA& { return obj._parameterNames; }
		);

		metaObject.addReflectProperty<MaterialParameterInfo, EMaterialParamType>(
			FlyweightStringA("ParameterType"),
			FlyweightStringA::Empty,
			EMaterialParamType{},
			[](MaterialParameterInfo& obj) -> EMaterialParamType& { return obj._parameterType; },
			[](const MaterialParameterInfo& obj) -> const EMaterialParamType& { return obj._parameterType; }
		);

		return metaObject;
	}
}
